async function main(): Promise<void> {
  console.log('go')
}
main()
  .then(() => console.log('Success'))
  .catch(console.error)
